name: "BundleScenes"
main: "gg.bundlegroup.bundlescenes.plugin.Main"
bootstrapper: "gg.bundlegroup.bundlescenes.plugin.Bootstrap"
version: "${version}"
api-version: "1.21.11"
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
