name: "BundleScenes"
main: "gg.bundlegroup.bundlescenes.Main"
version: "${version}"
api-version: "1.21.5"
dependencies:
  server:
    BundleEntities:
      load: BEFORE
    WorldGuard:
      load: BEFORE
      required: false
permissions:
  bundlescenes.command.conversion:
    default: op
